### ISSUE TITLE
Error : Vue is not a constructor

### ISSUE THREAD

**Issue by Filipal77** [warting/nfc-tools#9]
Hi,
I am facing a serious problem with NFC Tools in the Homey app.
Each time I tap "settings" and then "NFC Tools", I keep on having the following error message : "Error : Vue is not a constructor".
Could you please fix and update this ?
Thanks in advance for your help.

**Comment by mow87** [comment]
Hi,

I have same issue....

**Comment by Gizmopower1** [comment]
Same here....

**Comment by warting** [comment]
on it! :)

**Comment by warting** [comment]
Submitted for review.
Testers can opt in here: https://homey.app/a/se.warting.nfctools/test/

**Comment by mow87** [comment]
Error : Vue is not a constructor, seems to be solved but how do i add an nfc tag? When i open the app i get this see attached picture.
![Screenshot_20220407-005633_Homey](https://user-images.githubusercontent.com/89127586/162086336-c2cd7edb-ab9b-4c1e-92f3-8e680115b7f7.jpg)

**Comment by Gizmopower1** [comment]
I have been emailing with developer and he explained me..
The old homey Pre Early 2019 had an option to tap NFC stickers or card at the top of homey.
That hardware is now remowed on Early 2019 
See specs: https://support.homey.app/hc/en-us/articles/360015447093-Comparing-the-existing-Homey-Pro-models-

So for now there seems to be no option to get read, write NFC details into Homey early 2019

**Comment by warting** [comment]
1 option would be to use a mobile device to scan tags that forwards it to nfc-tools in homey.

**Comment by warting** [comment]
I have asked to get access to web api to be able to build a simular tool like 
https://companion.home-assistant.io/docs/integrations/universal-links/?_highlight=tag

work can be tracked here:
https://github.com/warting/nfc-tools/issues/11
